### ISSUE TITLE
How To Fetch URL Fragments

### ISSUE THREAD

**Issue by andytuch** [GoogleChromeLabs/quicklink#119]
I see a few issues with users that do not want to prefetch URLs with fragments and how to use ignore to stop it, but I want to prefetch URLs with fragments for my single page application. Quicklink is currently only using the base URL without the fragment information. Is there a way to allow it to use the full URL including fragment?

**Comment by dieulot** [comment]
It’s not currently doable but they’re working on it: [source](https://twitter.com/addyosmani/status/1170508263865012224?s=21).

**Comment by demianrenzulli** [comment]
Hi @andytuch, this is an old issue, but it seems like your requirement should now be possible thanks t #123, which has landed into the library by the end of last year.

Please, feel free to reopen if you need anything else.
