### ISSUE TITLE
"Uncaught TypeError: quicklink.listen is not a function"

### ISSUE THREAD

**Issue by edadams** [GoogleChromeLabs/quicklink#124]
**Describe the bug:**
Upon loading a page with the `quicklink` JS added and initialised as per the installation instructions, I get only this Chrome Dev Tools console error: 

```
Uncaught TypeError: quicklink.listen is not a function
```

**To Reproduce:**
You can try it on my [test website](https://heatheradams.co.uk) and open the dev tools console. Here's my initialisation code, taken directly from the README: 

```js
window.addEventListener('load', () =>{
  quicklink.listen();
});
```

Full snippet of code I use, which I have inserted as the last things before the `body` closes:

```html
<script src="/wp-content/themes/ha/js/quicklink.umd.js"></script>
<script>
  window.addEventListener('load', () =>{
    quicklink.listen();
  });
</script>
```

**Expected behavior:**
I assume `quicklink` should work!

**Versions:**
 - OS w/ version: macOS 10.14.6
 - Browser w/ version: Chrome 77.0.3865.90

**Additional context, screenshots, screencasts:**
n/a. This is probably so obvious but I can't figure out where I'm going wrong... I didn't use the npm installer method as my site's WordPress so manual installation suited my workflow better.

**Comment by tonyalaribe** [comment]
This might help  https://github.com/GoogleChromeLabs/quicklink/issues/81
Simply use 
```
quicklink();
``` 
instead of  `quicklink.listen()`

**Comment by dieulot** [comment]
The Readme currently references a future version of quicklink, to see the current API [it’s here](https://github.com/GoogleChromeLabs/quicklink/tree/d75188dc87507e3a7e759bd0988467071d7f765c).

**Comment by edadams** [comment]
That does explain it. Glad it wasn't me doing anything wrong. 😄 I'd have made a PR that changes the readme, but if that's up to date then it's clear you've got it under control. Closing with thanks!
