### ISSUE TITLE
quicklink.umd.js not available in the download package

### ISSUE THREAD

**Issue by Mexikaner9** [GoogleChromeLabs/quicklink#125]
unfortunately the script quicklink.umd.js is not in the download package.
Where can I get the script?

**Comment by demianrenzulli** [comment]
HI @Mexikaner9, hope you're well.

In the [installation section](https://github.com/GoogleChromeLabs/quicklink#installation) of the docs there's a reference to this. 

You can find the script at this URL: https://unpkg.com/quicklink@2.0.0-alpha/dist/quicklink.umd.js.

Hope it helps!
