### ISSUE TITLE
prefetch thirdparty site resource not work in PC Safari Or iOS Safari

### ISSUE THREAD

**Issue by danielding** [GoogleChromeLabs/quicklink#128]
Hey guys,

First of all thanks for the module, it looks great and something we are really interested in using it.
my question detail is below: 

**Describe the bug**
Hi, I hava a page, for example, a.com/a.html, in this page, I prefetch a resource in site b

`
// b.v1.html CORS header => Access-Control-Allow-Origin：* ; Cache-Control: max-age=31536000
fetch('b.com/b.v1.html')    

// b.v1.js CORS header => Access-Control-Allow-Origin：* ; Cache-Control: max-age=31536000
fetch('b.com/b.v1.js')    
`

then I visit page b.com/b.v1.html (who contains b.com/b.v1.js), I expect b.v1.html & b.v1.js from disk cache.

In Chrome, b.v1.html & b.v1.js is from disk cache, It's ok
**But** In PC Sarari or iOS safari, b.v1.html & b.v1.js is from network, not expected

did u meet this problem? And how to solve it? thanks

**Comment by danielding** [comment]
more info: https://onezero.medium.com/apple-is-trying-to-kill-web-technology-a274237c174d

**Comment by demianrenzulli** [comment]
Hi @danielding,

Some things to clarify first:

In Safari (and Webkit-based browsers in general), the browser cache is partitioned by origin. From [ITP docs](https://webkit.org/blog/7675/intelligent-tracking-prevention/): 

"Note that WebKit already partitions caches and HTML5 storage for all third-party domains."

This means that if `a.com` and `b.com` request a resource from `c.com`, they will be cached separately for each site. This implies that if `a.com` requests a resource from `c.com`, the cached copy of the resource can't be resource later by `b.com`.

In the scenario you've described, you are trying to prefetch third party resources, to be used later by the same origin that requested them in the first place (which is not the same scenario described before), so, in theory, this should just work.

On the other hand, prefetch [is not supported in Safari yet](https://caniuse.com/#search=prefetch), which means that `quicklink` will fallback to `XHR` in Webkit-based browsers.
For that reason, if the resource doesn't have a `cache-control: max-age` header set, the files will be fetched, but not stored in the cache.

In your example, though you're setting caching headers right. The only one I'm not seeing is the `Access-Control-Allow-Credentials=true` header, which Safari also asks for in 3rd-party requests of this kind. Could you check if the resource is being fetched correctly?

I put together [this test](https://quicklink-3rd-party.glitch.me/), which contains two links (same/cross origin respectively), with a `max-age` of 100 seconds. I could see both links fetched by `quicklink`, and, checking the server logs I didn't see any new request coming when clicking on them, which suggests they were picked up from the browser cache just fine.

Perhaps I'm missing something, so feel free to add more details.
Hope this helps.

**Comment by demianrenzulli** [comment]
Please, refer to @addyosmani's [comment](https://github.com/GoogleChromeLabs/quicklink/issues/101#issuecomment-558902044) about double-key caching. 
As said before, storage partitioning seems have been already applied to Safari browsers, but that shouldn't necessarily explain the behavior reported here (also tests seem to be working fine).

In any case, we can expect additional restrictions on third-party requests coming at some point, making these kind of scenarios less feasible.

**Comment by dieulot** [comment]
@demianrenzulli 
> On the other hand, prefetch [is not supported in Safari yet](https://caniuse.com/#search=prefetch), which means that `quicklink` will fallback to `XHR` in Webkit-based browsers.
> For that reason, if the resource doesn't have a `cache-control: max-age` header set, the files will be fetched, but not stored in the cache.

I tried in Safari 10.1, 11.1, 12.1, and 13.1, and it didn’t work. The file gets redownloaded.

I tried it on the [Google blog demo](https://keyword-2-ecd7b.firebaseapp.com/). I also tried modifying instant.page to use XHR. Didn’t work.

The one time it worked was on Safari 13.1, but that was because I had the prefetch experimental feature turned on. 😅 Are you sure you didn’t have the prefetch flag turned on?
