### ISSUE TITLE
Prefetch apis for SPAs

### ISSUE THREAD

**Issue by thearegee** [GoogleChromeLabs/quicklink#130]
Hey guys,

First of all thanks for the module, it looks great and something we are really interested in using it.
However we have a slightly different request, because our website is an SPA. I'm interested in using it here:

https://www.mrporter.com/en-us/mens/clothing

This could be used for either linking to Product details, or using filters. Ignoring how we detect intention, I'm interested in prefetching data from the relevant api.

This can be interpreted from the products part number or the filters path.

I've not had a huge think about how this could be implemented yet, but if for example we might want to be able to have different api prefetches based on an element type:

* Filters elements prefetch `GET /my-filters-endpoint/${filter-id}`
* Product elements prefetch `GET /my-product-endpoint/${product-id}`

You would need the ability to prefetch based on the element "type", maybe this could be done with data attributes or configure different `quicklink` instances based on `The DOM element to observe for in-viewport links to prefetch.`
 
I just wanted to start the conversation, would people be interested in this?

**Comment by dieulot** [comment]
[They’re working on it.](https://twitter.com/addyosmani/status/1170508263865012224?s=21)

**Comment by gilbertococchi** [comment]
Thanks Alexandre, @thearegee please check this pull request if it would satisfy your needs: https://github.com/GoogleChromeLabs/quicklink/pull/123

**Comment by thearegee** [comment]
@gilbertococchi this would be perfect for us, any progress on getting this merged?

**Comment by thearegee** [comment]
We used this PR: https://github.com/GoogleChromeLabs/quicklink/pull/123

To run some experiments to see if this was worth it, on this page: 
https://www.mrporter.com/en-be/mens/clothing

We added `quicklink` to the product grid, so as the user scrolled it would preload the APIs:
![image](https://user-images.githubusercontent.com/8751165/68389284-7cc21500-015a-11ea-820e-66271183ba57.png)

When the customer clicked the product, the API would already be cached:
![image](https://user-images.githubusercontent.com/8751165/68389381-b5fa8500-015a-11ea-98a1-7f2d255024ee.png)

This effective saved the user 250ms of waiting.

However we decided vs the bandwidth cost:
![image](https://user-images.githubusercontent.com/8751165/68389448-e2ae9c80-015a-11ea-9b8a-b6b44692618a.png)

It was not worth it. If interested this is our quick hack for how we referenced the API:
![image](https://user-images.githubusercontent.com/8751165/68389510-040f8880-015b-11ea-8c54-08bb9badccd1.png)

In this instance we will probably not follow this up.

**Comment by gilbertococchi** [comment]
It looks like ona Fast 3G Connection it would save approx 600-800ms TTFB time by downloading a 6-8KB JSON content. 
That's a pretty powerful improvement for Mobile but I guess it would be better handled with a Service Worker dedicated Caching Entry.

**Comment by thearegee** [comment]
This is a good point, I think it could be done with both. A prefetch on intersected elements and then cached with SW. At the moment our API is just too large for all the prefetching. So I need to do some work to slim this down.

I still think this is a great addition to the library though but we can't experiment further without: https://github.com/GoogleChromeLabs/quicklink/pull/123

**Comment by demianrenzulli** [comment]
Hi @thearegee, this is an old issue, but #123 has finally landed into the library around October 2020.

From your previous comment it seems like this was everything you needed to make this work. Perhaps others can find your tests useful for similar needs as well.

Closing this one. Please, feel free to reopen if you need anything else.
