### ISSUE TITLE
Provide details on how Quicklink works with cache-control headers and service workers

### ISSUE THREAD

**Issue by demianrenzulli** [GoogleChromeLabs/quicklink#140]
**Is your feature request related to a problem? Please describe.**

`Cache-Control` headers can affect prefetching, making the experience of implementing Quicklink vary, depending on the developer backend / CDN configuration, without s/he knowing what's happening.

We know [that](https://web.dev/link-prefetch/): _"Prefetched files are stored in the HTTP Cache, or the memory cache (depending on whether the resource is cacheable or not), for an amount of time that varies by browsers. For example, in Chrome resources are kept around for **five minutes**, after which the **normal cache-control rules** for the resource apply."_

This means that:

- `max-age=<XX seconds>`: Keeps the resource in the cache for 5' + XXs.
- `max-age=0`: Keeps the resource in the cache only for 5'.

And that (according to #21):

- `no-cache`: Doesn't prevent keeping the resource in cache.
- `no-store`: Prevents keeping the resource in cache.

Haven't tested yet [the rest](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) of the `cache-control` directives.

Additionally, it would be good to check how service workers treat prefetched files on strategies like `networkOnly()`. Intuitively, if the SW fails to retrieve the resource from the SW cache, it will check first in the prefetch cache, before going to the network.

**Describe the solution you'd like**
We can write some Glitch tests for each variation to make sure they work according to our assumptions, and documenting them more clearly.
Since this implementation doesn't seem to be defined in the spec and is browser-dependent, we might have to guess how each browser behaves.

**Additional context**
We've received questions from some developers, on cases where prefetched files were being requested by Quicklink, but not picked up by the browser when clicking on links. 

cc // @antoinebisch

**Comment by gijo-varghese** [comment]
@demianrenzulli `no-store` prevents the cache for sure. But I've also noticed it when `max-age=0`, even if it's under 5'.

**Comment by demianrenzulli** [comment]
Thanks for your comment @gijo-varghese!

When using `max-age=0`, I'm seeing prefetch working properly (at least in Chrome). 

Wondering in which browser you're testing this? Recall that [in browsers that don't support prefetch](https://caniuse.com/#search=prefetch), Quicklink will use other strategies as fallback (like `fetch()`). In those cases,  unless you have set caching headers in place, the prefetch will have no effect.

Testing this in Chrome:

1. Open [this site](https://mini-ecomm-quicklink.glitch.me/).
2. Check in CDT Network tab that in-viewport links are being prefetched.
3. Click on a product, and check that it's being retrieved from the prefetch cache.

If you take a look a the response headers of the page, it has `cache-control: public, max-age=0`.

Perhaps, if you can share some sample code, we can take a closer look at it.

**Comment by gijo-varghese** [comment]
@demianrenzulli Ok. I'll double-check it. So far, only `no-store` causes issue right?

**Comment by demianrenzulli** [comment]
Hi @gijo-varghese! That seems to be the case.

In fact, if you open [this link](https://quicklink-no-store.glitch.me/) and run the test suggested before, you'll notice that in-viewport links are fetched, but, when clicking on them, they are not picked up from the prefetch cache.

If you inspect the response headers for the product page, the new demo uses `Cache-Control: no-store`, which is prevented that from happening.

**Comment by demianrenzulli** [comment]
We've just released a new guide covering prefetching techniques with service workers:

https://dev.to/drenzulli/prefetching-techniques-with-workbox-3bpc
