### ISSUE TITLE
Quicklink site - Logo not displayed correctly in FF 70

### ISSUE THREAD

**Issue by demianrenzulli** [GoogleChromeLabs/quicklink#143]
The  [SVG logo](https://quicklink-6a87b.firebaseapp.com/assets/images/logos/quicklink.svg) is not displayed correctly in Firefox 70 (see attached screenshot).

![image](https://user-images.githubusercontent.com/15170359/69909600-48ddb680-13cb-11ea-8b6e-bf5bb9bd827c.png)

To reproduce: open the logo in the browser, of the site: https://quicklink-6a87b.firebaseapp.com/

cc // @addyosmani

**Comment by addyosmani** [comment]
Good catch! I saw this after we landed the site PR and pushes some fixes to the SVG. Is the latest deploy fixed for you?

![image](https://user-images.githubusercontent.com/110953/69919224-955add80-142f-11ea-9dda-be4600f679fd.png)

**Comment by demianrenzulli** [comment]
Works now, perfect! 👌
