### ISSUE TITLE
alpha version 

### ISSUE THREAD

**Issue by ale82to** [GoogleChromeLabs/quicklink#154]
is there any crx to test alpha version 2.0 thanks

**Comment by demianrenzulli** [comment]
Hi @ale82to! 

If you are asking for a Chrome Extension to be able to test Quicklink 2.0, the current [Quicklink Chrome Extension](https://chrome.google.com/webstore/detail/quicklink-chrome-extensio/epmplkdcjhgigmnjmjibilpmekhgkbeg) uses that version under the hood.

You can check the [code](https://github.com/demianrenzulli/quicklink-chrome-extension/blob/2b3a9bc6545346e4724942a63b79ddcb98fe830b/src/init.js#L20), where `quicklink.listen()` is being used to initialize the library, as it's  the way of doing it in the new version.

Is that what you're looking for?

**Comment by ale82to** [comment]
yes thank you amazing speed increase is really notociable

**Comment by demianrenzulli** [comment]
Awesome @ale82to! Hope you enjoy the new version, closing this one now 👍
