### ISSUE TITLE
getting temp ban on some website 

### ISSUE THREAD

**Issue by ale82to** [GoogleChromeLabs/quicklink#157]
first of all I really love this extension anyway on some website like apkmirror or xda developer i sometimes get temporary ban
today I even got captcha verification on Amazon, never happened in my life. 
is there any fix other than disabling the extension for the problematic websites, thanks.

**Comment by demianrenzulli** [comment]
Hi @ale82to! Thanks for reaching out.

I think you're talking about the Chrome Extension, is that correct? If so, are you  ok with me moving this question to the [Quicklink extension repo](https://github.com/demianrenzulli/quicklink-chrome-extension), so we can continue from there?

Also, if you have any screenshots of the behavior you're observing that would be useful.

Thanks a lot!

**Comment by demianrenzulli** [comment]
Closing this one, so we can continue this conversation in [the corresponding issue](https://github.com/demianrenzulli/quicklink-chrome-extension/issues/1) at the extension repo.
