### ISSUE TITLE
Complimentary lib

### ISSUE THREAD

**Issue by jeremy-coleman** [GoogleChromeLabs/quicklink#16]
https://github.com/glixlur/snap

Prefetch on hover 
Just a thought

**Comment by addyosmani** [comment]
Nice! It looks like this may be worth including in the related projects section. Could you describe how it differs from InstantClick? (README mentions bug-fixes)

**Comment by aolko** [comment]
seems to be dead

**Comment by addyosmani** [comment]
It does appear the above library hasn't been updated in quite some time (commits appear to stop in 2016). I'm going to close this issue. If folks strongly feel specific complimentary libraries are worth highlighting in the README, happy to consider PRs ❤️
