### ISSUE TITLE
Custom options

### ISSUE THREAD

**Issue by Mexikaner9** [GoogleChromeLabs/quicklink#161]
How about enabling custom options?
For example:
only preload
dont preload
preload order:

**Comment by demianrenzulli** [comment]
Hi @Mexikaner9! 

Thanks for submitting your question. Just want to try to understand this request better:

When you talk about "preload" are you thinking on adding support for `<link rel="preload">`, in addition to the current supported functionality (based on `<link rel="prefetch">`), or perhaps you meant adding some options to control the current prefetch behavior?

Regarding order of requests sent: we've already explored this in #72, and decided not to move forward with that request, the reason being that in the current state, it's hard to guarantee that requests will be sent in the requested order.
If you know about a use case when having control on the order of request is necessary for it to work properly, we could perhaps re-open that FR, so it can be evaluated in future releases.

Thanks!

**Comment by demianrenzulli** [comment]
Hi @Mexikaner9! 

Since we haven't received a response from this, I'm closing this now, but  feel free to re-open if you have any additional details to share on my previous comments.

Cheers.
