### ISSUE TITLE
React: routes are not preloaded

### ISSUE THREAD

**Issue by ryands17** [GoogleChromeLabs/quicklink#186]
**Describe the bug**
Routes are not preloaded if they are configured in the following manner:

**To Reproduce**

- Create routes

```ts
import { withQuicklink } from 'quicklink/dist/react/hoc.js'

export const routes = {
  home: {
    path: '/',
    element: withQuicklink(React.lazy(() => import('pages/Home'))),
  },
  about: {
    path: 'about',
    element: withQuicklink(React.lazy(() => import('pages/About'))),
  },
  contact: {
    path: 'contact',
    element: withQuicklink(React.lazy(() => import('pages/Contact'))),
  },
}
```

- Add those to `react-router`

```ts
import { useRoutes } from 'react-router-dom'

export const AppRoutes = () => {
  const renderRoutes = useRoutes(
    Object.values(routes).map((route) => ({
      path: route.path,
      element: <route.element />,
    }))
  )
  return renderRoutes
}
```

**Expected behavior**
Route chunks should be preloaded.

**Version:**
 - OS w/ version: [Linux]
 - Browser w/ version [e.g. Chrome 81]

**Comment by anton-karlovskiy** [comment]
@ryands17 cc @addyosmani @demianrenzulli 

Thank you for filing this issue!
My apologies for the delay.

Could you possibly share the example project with me?
If you could create some demo project and show me, I would be happy to address that issue.

**Comment by ryands17** [comment]
@anton-karlovskiy 👋 
Here's the repo: https://github.com/ryands17/quicklink-repro

**Comment by anton-karlovskiy** [comment]
@ryands17 

Thank you! Let me check and update you.

**Comment by anton-karlovskiy** [comment]
@ryands17 

I've fixed at https://github.com/ryands17/quicklink-repro/pull/1 but I would like your confirmation.
Once it's confirmed, hopefully we can close this issue. Thank you.

**Comment by ryands17** [comment]
@anton-karlovskiy Yes it works perfectly! 
Also just a side question, if I want to prefetch on link hover instead of after page load, I would need to use the programmatic API as specified [here](https://github.com/GoogleChromeLabs/quicklink#programmatically-prefetch-urls) or is there any other way for SPA's?

**Comment by anton-karlovskiy** [comment]
@ryands17 Thank you for your confirmation.

> Also just a side question, if I want to prefetch on link hover instead of after page load, I would need to use the programmatic API as specified here or is there any other way for SPA's?

Let me discuss internally and update you shortly. Thank you.

**Comment by anton-karlovskiy** [comment]
Hi @ryands17 

We created this project for the same use case. https://github.com/anton-karlovskiy/cra-hover-prefetch
Could you please check it and give me feedback? Thank you.

It was ejected create-react-app for configuring webpack-route-manifest.
Probably it was setup with the old [webpack-route-manifest](https://github.com/lukeed/webpack-route-manifest) which does not allow us to use `window.__rmanifest`.

**Comment by anton-karlovskiy** [comment]
@addyosmani @demianrenzulli cc @ryands17 

Hi folks,
I think we can close this issue.

**Comment by anton-karlovskiy** [comment]
@ryands17 Could you possibly give us feedback on https://github.com/anton-karlovskiy/cra-hover-prefetch?

**Comment by ryands17** [comment]
Hey @anton-karlovskiy 👋 
Yup. It works great! https://github.com/ryands17/prefetch-routes
