### ISSUE TITLE
React Routes are not getting preloaded

### ISSUE THREAD

**Issue by neerajdixit27** [GoogleChromeLabs/quicklink#187]
**Before you start**
I am not able to preload React Route Chunks (JS, CSS) 

**Describe the bug**
```
import { withQuicklink } from 'quicklink/dist/react/hoc.js';

const options = {
  origins: []
};

const routes = [
  /*
  NOTE: opportunities routes disabled for now
  {
    id: 'test1-route',
    path: '/test1',
    component: () => import'../containers/Test1'),
  },
  */
  {
    id: 'test2',
    path: '/test2',
    component: () => import( '../containers/Test2'),
  },
];

<Suspense fallback={<div>Loading...</div>}>
    <Switch>
      {
        routes.map((routeConfig = {}, index) => {
          const { path, component: routeComponent, config = {} } = routeConfig;

          const route = {
            path,
            component: withQuicklink(lazy(routeComponent), options),
            exact: config.isExact,
          };

          return (
            <Route key={index} {...route} />
          );
        })
      }
    </Switch>
  </Suspense>
```

Webpack Config

```
// other config
  plugins: [
    new RouteManifest({
      minify: true,
      filename: 'rmanifest.json',
      routes: {
        '../containers/Test1': '/test1',
        '.../containers/Test2': '/test2'
      }
    }),
]
```

I have a hyperlink on Test1 Container which refers to "/test2" , but i see test2 related chunks are not preloaded and are loaded when i navigate to that link I am able to see the value for window.__rmanifest in the console. 

Thanks for your help in advance. This is really a Cool plugin

**Expected behavior**
React Router Chunks should be Preloaded

**Version:**
 - Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by anton-karlovskiy** [comment]
@neerajdixit27 cc @addyosmani @demianrenzulli 

Thank you for filing this issue!
My apologies for the delay.

Could you possibly share the example project with me?
If you could create some demo project and show me, I would be happy to address that issue.

**Comment by anton-karlovskiy** [comment]
@neerajdixit27 

Could you please have a look at the fix from https://github.com/GoogleChromeLabs/quicklink/issues/186?

**Comment by demianrenzulli** [comment]
Hi @neerajdixit27, this has been opened for a while, without any activity. 
It seems like the solution that @anton-karlovskiy should fix your problem, but, if not, please, feel free to reopen.

It would be great to hear about your experience with the Quicklink + React integration.
