### ISSUE TITLE
npm warning

### ISSUE THREAD

**Issue by jimblue** [GoogleChromeLabs/quicklink#189]
**Describe the bug**

Getting this warning while installing NPM packages:

```bash
npm WARN quicklink@2.0.0 requires a peer of react@^16.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN quicklink@2.0.0 requires a peer of react-dom@^16.8.0 but none is installed. You must install peer dependencies yourself.
````

**To Reproduce**
Just run `npm install`

**Expected behavior**
As react is not necessary to use Quicklink, this warning shouldn't show up.

Can you please move `react` and `react-dom` from `peer dependencies` to `dev dependencies`.

Thanks

**Comment by Eben-Hafkamp** [comment]
Nothing happening about those peerDeps then, I'm prefetching fine in a hybrid Vue setup. Not going to install React to remove 2 warnings lol any updates?
