### ISSUE TITLE
quicklink is not defined

### ISSUE THREAD

**Issue by KasiaGizinska** [GoogleChromeLabs/quicklink#190]
**BUG**
Hi! When I try to import quicklink or { listen } as a node_module I get an error "quicklink is not defined". When I import it as a file from the project folder everything works great. Any idea why it's happening?

**To Reproduce**
Import quicklink as ES Module:
`import { listen, prefetch } from 'quicklink';`

Use quicklink in a project:
`quicklink.listen();`

**Version:**
 - Quicklink 2.0
 - Yarn used to add package

**Comment by olegatro** [comment]
```js
import {listen} from 'quicklink';
//...

listen();
```

**Comment by olegatro** [comment]
@KasiaGizinska ping

**Comment by demianrenzulli** [comment]
Hi @KasiaGizinska! Thanks for filing this.

@olegatro solution should work fine. Closing this one. Feel free to reopen if you have any additional questions.
