### ISSUE TITLE
Quicklink vs Workbox

### ISSUE THREAD

**Issue by revanth0212** [GoogleChromeLabs/quicklink#196]
Hey guys. I am a developer working on the [pwa-studio](https://github.com/magento/pwa-studio) open-source project from Adobe. Let me begin by telling you how good the `quicklink` package is, it is simply amazing. So little work for the developer but so much in return. Amazing work. Well done.

Let me give you a small background of what `pwa-studio` is. It is a progressive web app toolkit for building E-Commerce applications. Like all PWAs, our app relies on Service Workers to help provide a good experience in mobile environments.

Our Service Worker is based on the Workbox toolkit from Google. We have implemented pre-fetching into the Service Worker using the workbox webpack plugin. At build time, the webpack plugin modifies the SW code to inject a list of pre-fetch assets that the build process has emitted. So when the SW loads, it downloads all possible build assets needed for the app to render. Also, we have implemented a [custom API](https://github.com/magento/pwa-studio/pull/1938/) over `MessageChannel` to let the SW know if the App needs anything pre-cached like an image or document that might not have an HTML tag since they can be dynamic links.

If I read and understand correctly, `quicklink` is a library that aims to make page transitions faster by pre-fetching required assets ahead of time. Do you think, one can find `quicklink` useful when they already have `workbox` prefetching installed? What advantages can `quicklink` offer in such situations?

Thank you.

**Comment by demianrenzulli** [comment]
Hi @revanth0212! 

First of all, thanks a lot for your interest in `quicklink`!

I have the feeling that you were referring to ["precaching" with Workbox](https://web.dev/precache-with-workbox/), not "prefetching with Workbox" (please, correct me if I'm wrong).

If that's the case, the short answer to your question would be: "prefetching" techniques (e.g. using a library like `quicklink`, or  inserting`<link rel="prefetch">` tags directly in pages) are, in most cases, **complementary** to "precaching" techniques in the service worker (caching static assets at the service worker "install" event, with or without using Workbox).

So, why are they complementary?

By default, `quicklink` will prefetch documents (.html pages) for every link that comes into the view. Imagine a product listing page. As you scroll, the documents (.html) pages for those pages are prefetched by `quicklink` and added to the browser cache for a short period of time.

In this case, we are talking only about the html page. If you had already added the static assets that the page will request (CSS, JS, etc), via Workbox precaching, then, by the time the user clicks on the link both the page (thanks to `quicklink`) and the assets (thanks to Workbox) will be in the cache, making that navigation load much faster.

We've recently released a blog post covering this in detail with @jeffposnick and @gilbertococchi: https://web.dev/instant-navigation-experiences/.

Please, let me know if I understood your question well, or I'm missing any important details (also, folks tagged in this thread, feel free to chime in).

**Note:** I'm not very familiar with the architecture approach of PWA Studio. I'm assuming the sites are multi-page-apps. If the sites are single-page-apps, my answer will be a little bit different, but I don't want to make this thread longer, so let me know if you want to know more.

It would be great to talk about ways in which PWA studio can take advantage of `quicklink`, so, please feel free to reach out to us if you want to know more.

cc // @addyosmani

**Comment by gilbertococchi** [comment]
Hi @revanth0212, thanks for raising these interesting questions!

Quicklinks is meant to be not a substitution of what you've already done on the SW Static Assets precaching but rather an improvement of precaching the last mile of resources (in this case the HTML or the API calls) that are not a good fit for a Manifest precaching.

In the case of the PWA Studio site I believe the benefit would be in PDP from PLP HTML related Requests prefetching when a PDP target become visible.

So imagine I browse a PLP page, then the Product item become visible, the Browser is in idle state and the connection is fast enough Quicklink would trigger the HTML request to the PDP HTML page (saving TTFB time if user will then click on the target).
We are also looking for feedback for a Quicklink PR that would allow to specify a callback https://github.com/GoogleChromeLabs/quicklink/pull/123 that it could be used to trigger the graphql requests related to the Product Items but I am curious to hear from you if it would make sense to prefetch them.

Screenshot below of the Network requests I am talking about
![Screenshot 2020-08-06 at 14 11 36](https://user-images.githubusercontent.com/329023/89530490-dee59e80-d7ee-11ea-8a13-93eb9558abee.png)

Summarizing with Quicklinks PDP HTML+ API prefetching + the Service Worker precaching on common assets you have in place in theory it should be possible to allow an almost instantaneous load of any Product Detail Page from a PLP Page.

Gil

**Comment by gilbertococchi** [comment]
Hi @revanth0212, please let me know if you would like more touching points of how Quicklinks would help navigating PDPs faster on PWA Studio sites.

Here you can find another example that highlights how Prefetching the **graphql?query=query(productDetail...** API URL when a user would stop scrolling on a PLP before clicking on the object would drastically improve PDP FCP and LCP time by reducing the API Time that is mostly TTFB time.

Do you think that prefetching API calls can be experimented? Are there potential server performance implications from additional graphql requests being triggered this way?

Gil

**Comment by revanth0212** [comment]
Hello @gilbertococchi and @demianrenzulli. Thanks, guys for replying on the thread. I appreciate your help. Sorry for the late response guys.

Apps built using the PWA Studio are most likely going to be single-page applications. Right out of the box, all the pages/routes render the same HTML file. So we added logic into the SW that returns the same HTML file from the cache even if the HTML file is not cached on the same route. 

For instance, the route `aurora-sleeveless-blouse.html` was never cached but the file was fetched in `4ms`.

![image](https://user-images.githubusercontent.com/35203638/91740231-9f556c80-eb78-11ea-818a-13c3c632ca81.png)

Coming to GQL caching, we tried it using Apollo and realized it is good to have feature but increases the network usage which our end-users might not wish to have.

We have deferred having this conversation about pre-fetching HTML and GQL when we have a full-fledged SSR and I am going to push `quicklinks` because it can solve such features with less work and more clarity.

Thanks for the replies guys, I will keep you posted with any developments in this topic.

You have got a wonderful package here, nice work, and thank you.

**Comment by demianrenzulli** [comment]
Hi @revanth0212! I think you've made a great summary of the reasons behind the decisions you've made, so I don't think we have more to add.

Last week a [new feature](https://github.com/GoogleChromeLabs/quicklink/pull/201) was approved, allowing you to generate a dynamic URL for in-viewport links. This might give you more flexibility at the moment of integrating the library in SPA architectures. You can check a demo [here](https://github.com/GoogleChromeLabs/quicklink/blob/224df779d233186df6b5d5a85b815c943dcb890c/demos/hrefFn/hrefFn_demo.html#L27).

I'll close this issue now, but when the time comes and you want to resume a conversation about the benefits of Quicklink for PWA Studio, feel free to reopen it.
