### ISSUE TITLE
`prefetch` in combination of `Cache-Control`

### ISSUE THREAD

**Issue by beldur** [GoogleChromeLabs/quicklink#21]
Is it necessary to set the `Cache-Control` Header to a specifc value to take advantage of prefetching?

On the demo Site `https://keyword-2-ecd7b.firebaseapp.com/` I can see a `Cache-Control` Header of `max-age=3600`. Would `quicklink` also work with a `Cache-Control: no-cache` header?

**Comment by addyosmani** [comment]
If a resource in Chrome is prefetched with `<link rel=prefetch>` (via HTML or the header), it will be kept around for 5 minutes. This lasts until the resource has been consumed, at which point the normal cache-control rules for the resource will apply. 

That's to say, if a resource has `Cache-Control: no-cache` my understanding is those prefetched resources need to be kept around until next navigation, even if they are not cacheable.

**Comment by beldur** [comment]
Hi Addy,

I was trying to find out why prefetch did not work in my case.

The problem was I had `no-store` in my `Cache-Control` Header. After removing it, it works even with `no-cache`.

Thanks for your answer!

**Comment by Nithanaroy** [comment]
Is there a way change the default 5 minutes max-age from the client side as part of the request using `<link rel />` or quicklink?

**Comment by 19Qingfeng** [comment]
> If a resource in Chrome is prefetched with `<link rel=prefetch>` (via HTML or the header), it will be kept around for 5 minutes. This lasts until the resource has been consumed, at which point the normal cache-control rules for the resource will apply.
> 
> That's to say, if a resource has `Cache-Control: no-cache` my understanding is those prefetched resources need to be kept around until next navigation, even if they are not cacheable.

hi @beldur ,I have searched many places, but I haven't seen any explanation about the expiration of prefetch. May I ask if there is a specific documentation for 5 minutes? Thank you

**Comment by beldur** [comment]
The time comes from you `Cache-Control` header. If you set it to `max-age` 3600, that would mean 5 minutes.
