### ISSUE TITLE
Skip hidden elements

### ISSUE THREAD

**Issue by midzer** [GoogleChromeLabs/quicklink#249]
Hi quicklink-team,

**Is your feature request related to a problem? Please describe.**
On some of my pages there are internal links are in the viewport which are are `visibility: hidden` (for example in a burger button). I don't want them to be fetched.

**Describe the solution you'd like**
I like those links to be skipped at first. When they become visible, prefetch them as always.

Have a nice week
midzer

**Comment by passionInfinite** [comment]
@midzer Maybe using the custom filter you can ignore those links. Please see https://github.com/GoogleChromeLabs/quicklink#custom-ignore-patterns for more info on it.

**Comment by midzer** [comment]
Thanks for your answer, @passionInfinite!
