### ISSUE TITLE
Target links by data attribute

### ISSUE THREAD

**Issue by tlgimenes** [GoogleChromeLabs/quicklink#270]
**Is your feature request related to a problem? Please describe.**
Hi folks. First of all, great work!

I'm using this library in an ecommerce and I'd like to enable prefetching only on certain anchor elements. The reasoning behind this is that I want to preload product pages only, but not institutional or collection pages (for saving data & infra costs). 

**Describe the solution you'd like**
I'd like to be able to pass the query element selector applied in [here](https://github.com/GoogleChromeLabs/quicklink/blob/e6565ed12b4872b67a862b9fe2198fe0d73cb485/src/index.mjs#L174) so I can query `a[data-prefetch=true]` or something like this.

**Additional context**
Thanks!

**Comment by hirasso** [comment]
Hey @tlgimenes , you can use [`options.ignores`](https://github.com/GoogleChromeLabs/quicklink#optionsignores) to achieve this:

```js
quicklink.listen({
  ignores: [
    (uri, elem) => !elem.matches("[data-prefetch]"),
  ],
});
```
