### ISSUE TITLE
Fix Prerender Support

### ISSUE THREAD

**Issue by gilbertococchi** [GoogleChromeLabs/quicklink#348]
Now QuickLink limits Prerender to 1 URL and to Same Origin only.

- [ ]  1 URL to Prerender limit should be removed
- [ ] Same Origin should be removed or it should include Same-Site Cross-Origin use case as well

@hadyan  @addyosmani FYI

**Comment by gilbertococchi** [comment]
@hadyan  @addyosmani FYI

**Comment by XhmikosR** [comment]
@kireerik please make a new issue with as much info as possible.

**Comment by hadyan** [comment]
> @kireerik please make a new issue with as much info as possible.

+1 @kireerik it will be interesting to take a look at the issue that you are facing with the `prerender` option if you can share more details (even better if you have a demo page) in the new issue. Thanks.

**Comment by kireerik** [comment]
Sure. I have created the new issue:
- #390
