### ISSUE TITLE
Ignore elements?

### ISSUE THREAD

**Issue by aolko** [GoogleChromeLabs/quicklink#38]
Can you ignore specific elements? "Quicklink everything but [...]" case

**Comment by lukeed** [comment]
We will be adding a `filter` option that will assert against the URL(s) in question. Although it's not exactly the same you're requesting, I think that should work for you, right?

If you _needed_ to rely on the DOM (aka, can't know the ignore patterns ahead of time), this would be possible:

```js
// assumes your links are <a href="..." noprefetch /> to avoid
const toIgnore = Array.from(document.querySelectorAll('a[noprefetch]'), x => x.href);

// run (future) quicklink
quicklink({
  filter: url => !toIgnore.includes(url)
})
```

**Comment by aolko** [comment]
alright, ETA for `filter`?

**Comment by schollz** [comment]
This is really useful if one of the links is "/logout" which may cause deletion of the cookies, etc.

Looking forward to it!

**Comment by addyosmani** [comment]
Fixed by https://github.com/GoogleChromeLabs/quicklink/commit/1ff35548fe61df8504c118db97e3c88c825e3438. `origins` and `ignores` will be in the next release so filtering will be available shortly.
