### ISSUE TITLE
Does not work as a traditional JS resource – Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by olpeh** [GoogleChromeLabs/quicklink#39]
Hello, this looks like a very handy library. However, I'm having trouble using it **without** using it as an ES-module.

**My source code:**
```
<script src="https://unpkg.com/quicklink@0.1.2/dist/quicklink.js"></script>
<script>
  quicklink();
</script>
```

**The output:** 
```
quicklink.js:1 Uncaught ReferenceError: module is not defined
    at quicklink.js:1
(anonymous) @ quicklink.js:1
(index):142 Uncaught ReferenceError: quicklink is not defined
    at (index):142
```

**Expected result**
I would expect it to work since the readme says so.

**Comment by lukeed** [comment]
Hey, for browser/UMD usage thru unpkg.com, you should use this asset: `https://unpkg.com/quicklink@0.1.2/dist/quicklink.umd.js`

The one you requested is the Node/CommonJS version

**Comment by olpeh** [comment]
Oh, okay thanks, that works. Maybe that could be written in the readme?

**Comment by lukeed** [comment]
For sure, will do – thanks!

**Comment by HiFaraz** [comment]
@lukeed the README current advises to use `<script src="dist/quicklink.js"></script>`. Should that also be changed to `<script src="dist/quicklink.umd.js"></script>`? Doing that fixed a similar error in my app. Happy to submit a PR for this :)

**Comment by lukeed** [comment]
@HiFaraz Oh, yes! That file is for CommonJS. Would you like to do a PR for the README fixes? Everything inside a `<script>` tag should be the UMD file – except the example(s) with ESM imports.

**Comment by HeikoMamerow** [comment]
Sorry for silly OT question, but why did you get the common js file this "umd"?

**Comment by HiFaraz** [comment]
@lukeed I'll submit a PR in the next couple of days.
