### ISSUE TITLE
Option to limit the maximum number of prefetched requests

### ISSUE THREAD

**Issue by jadjoubran** [GoogleChromeLabs/quicklink#4]
It would be nice to limit the number of links that will be prefetched
which can also default at a sane number.

Proposed API: `options.limit`

Would love to get your feedback on naming & default limit

**Comment by jadjoubran** [comment]
I started working on this, and I need some clarification
should I implement `maxPrefetches` or `maxParallelPrefetches`?
the way I understood is that `maxPrefetches` is the maximum amount links to prefetch in total (during the page lifecycle)
and `maxParallelPrefetches` is the maximum amount of links to prefetch concurrently (in parallel)

Also, do you think it makes sense to be called `limit` or one of the 2 options above?

**Comment by addyosmani** [comment]
I like the simplicity of `limit`, but I don't have a strong opinion on naming. `maxConcurrentPrefetches` is another one.

In retrospect, given the browser and server configuration will impact what "parallel" or "concurrent" mean, limit might make the most sense.

**Comment by xavierfoucrier** [comment]
Hi everyone, just see the 1.0.1 release :tada: and joining the conversation to give my opinion.

I am working with the team of @barbajs and we have a module called `@barba/prefetch`, inspired by quicklink, that prefetch in-viewport links of a web page: https://barba.js.org/docs/v2/user/prefetch.html.

We already discussed about having a `limit` parameter in this module, but in most cases, we noticed that the viewport doesn't really contain more than 5/10 "un-prefetched" links at a time. We wan't to keep BarbaJS **as simple as possible**, so this feature is not implemented yet.

From my point of view, if you decide to add this option, you should go with `limit` to keep the name simple. That make sense.

Keep this lib moving forward! :wink:
