### ISSUE TITLE
Requests blocked because of mixed content

### ISSUE THREAD

**Issue by ezeveliz** [GoogleChromeLabs/quicklink#45]
When using this locally it works great, but when in production, the prefetched links get blocked because of 'mixed content' and I get the 'This page is trying to load scripts from unauthenticated sources' alert.

This comes up in the console:
Mixed Content: The page at 'https://livi.com.ar/evaluacion?id=24' was loaded over HTTPS, but requested an insecure prefetch resource 'http://livi.com.ar/evaluacion?id=14'. This request has been blocked; the content must be served over HTTPS.

Any help?

**Comment by lukeed** [comment]
Hey, I assume `livi.com.ar` is your domain, correct? Your links should match the current protocol, as this is not something `quicklink` can do for you. I'd recommend changing your self-pointing links so that they all start with `https://...` (because you're using HTTPS) or to `//...` to more easily interchange HTTP and HTTPS scenarios. 

The first is preferred, but the 2nd might make your life easier, depending on what you're doing.

**Comment by ezeveliz** [comment]
Hey @lukeed thanks, I realized it was my fault, I fixed all the problems except one: I have some a tags that when clicked open a modal and I setted its href attribute to 'javascript:' so the page won't jump when clicked.
Do you know what could I do with those?

**Comment by lukeed** [comment]
Great!

We have a new version coming out very soon that will allow you to ignore links based on particular URL patterns or DOM attributes. It's called the `ignores` option & has just been merged to master.

When that is published, you can do this:

```js
quicklink({
  ignore: /javascript:/
})
```

Or, if those links had a certain className or attribute on them:

```js
// <a href="javascript:void" noprefetch">Hello</a>
quicklink({
  ignores: (url, elem) => elem.hasAttribute('noprefetch')
});
```

The `ignores` can also be an Array of multiple RegExps _and_ functions.

**Comment by ezeveliz** [comment]
Thanks!

**Comment by addyosmani** [comment]
1.0.0 is now live with the new `ignores` option available: https://www.npmjs.com/package/quicklink :)
