### ISSUE TITLE
Add option to ignore href with target="_blank"

### ISSUE THREAD

**Issue by jimblue** [GoogleChromeLabs/quicklink#46]
First thank you for this nice plugin.

Something that could improve it is an option to ignore all link that redirect outside of the current website.

It could be done with a new option to ignore link href with `target="_blank"`

Cheers

**Comment by jimblue** [comment]
I've just read issue #31 that report the same problem with an interesting solution.
It could be nice to have 2 options then, one for same domain, one for target="_blank".

**Comment by addyosmani** [comment]
I think the `ignores` filtering capabilities being introduced in #32 would solve this.

**Comment by jimblue** [comment]
I agree. Can be close.
Thanks for you fast answer!
