### ISSUE TITLE
Option to customize IntersectionObserve constructor option

### ISSUE THREAD

**Issue by HOUCe** [GoogleChromeLabs/quicklink#47]
It would be nice to customize IntersectionObserve constructor option. 

Proposed API: options.observerOptions. 

Would like to get your feedback on naming and ready to take a PR if needed

**Comment by lukeed** [comment]
We'll likely be solving this through #48

**Comment by demianrenzulli** [comment]
Hi folks,

Proceeding to close this older issue. At this point, IntersectionObserver behavior can be configured by [options.priority](https://github.com/GoogleChromeLabs/quicklink#optionspriority) and [options.limit](https://github.com/GoogleChromeLabs/quicklink#optionslimit), as can be seen [here](https://github.com/GoogleChromeLabs/quicklink/blob/d5d5ca565c505953b73a9494a6c344948872dc23/src/index.mjs#L73).

If you guys think there's need for more configuration options, feel free to reopen this issue, or create a new one.

Cheers.
