### ISSUE TITLE
network idle callback demo not working

### ISSUE THREAD

**Issue by jadjoubran** [GoogleChromeLabs/quicklink#5]
It seems the error is from the module.export in the network idle callback loaded from unpkg
(https://unpkg.com/network-idle-callback@1.0.1/lib/index.js)

![screen shot 2018-12-05 at 17 35 37](https://user-images.githubusercontent.com/2265232/49528439-39a95300-f8b4-11e8-9cfd-d900f6c69ec2.png)
![screen shot 2018-12-05 at 17 35 49](https://user-images.githubusercontent.com/2265232/49528443-3d3cda00-f8b4-11e8-8694-0bad99e55114.png)

**Comment by addyosmani** [comment]
@jadjoubran This should be fixed now. If you get a chance, could you verify there aren't further bugs you're experiencing? Cheers!

**Comment by jadjoubran** [comment]
Confirmed it's working 👍

**Comment by addyosmani** [comment]
Thank you!
