### ISSUE TITLE
Ability to exclude some links from prefetching

### ISSUE THREAD

**Issue by adelura** [GoogleChromeLabs/quicklink#50]
Thank you for such a nice library :)

One of the links which are visible on my website is `/logout` link. As you can imagine this link log me out from the web application. Is there ability to exclude that link from being prefetched 😄?

**Comment by MIROPRAV** [comment]
суббота, 15 декабря 2018 г. пользователь Artur Delura <
notifications@github.com> написал:

**Comment by addyosmani** [comment]
Our pleasure! 

Ignoring specific links or patterns of links can now be accomplished in quicklink@1.0.0 using the `ignores` feature: https://github.com/GoogleChromeLabs/quicklink#recipes

```js
// This example will ignore all requests to:
//  - all "/api/*" pathnames
//  - all ".zip" extensions
//  - all <a> tags with "noprefetch" attribute
//
quicklink({
  ignores: [
    /\/api\/?/,
    uri => uri.includes('.zip'),
    (uri, elem) => elem.hasAttribute('noprefetch')
  ]
});
```

For ignoring the `/logout/` path, something like this should work:

```js
quicklink({
  ignores: [
    /\/logout\/?/,
  ]
});
```

**Comment by adelura** [comment]
Thank you, and sorry for missing this information in the readme. I didn't read thoroughly this section and I was searching for "exclude".
