### ISSUE TITLE
Do not preload links (with anchors) to same site I am already on

### ISSUE THREAD

**Issue by janpio** [GoogleChromeLabs/quicklink#52]
I added quicklink to a play project of mine, https://ionic.zone.

On https://ionic.zone/content, I have a table of contents with loads of page internal links with an anchor (`#anchor`) to headlines below. It looks like quicklinks tried to preload all of those:

![image](https://user-images.githubusercontent.com/183673/50060659-eb8b2e00-0196-11e9-9b0a-e71a0076a99f.png)

Wouldn't it make sense to not preload links to the page I am already viewing?

**Comment by addyosmani** [comment]
One way to solve this is using the new `ignores` field which supports specifying a RegExp, Array or function of criteria to not prefetch URLs. You could set it to not prefetch any URLs with a anchor/fragment.

**Comment by addyosmani** [comment]
We've added a note in the docs around how to use `ignores` to ignore anchors and URL fragments that can now be found here https://github.com/GoogleChromeLabs/quicklink#custom-ignore-patterns. Hopefully that helps ❤️

**Comment by janpio** [comment]
Thanks. Can I limit that to the local domain? (So only # links for my own domain are ignored)
