### ISSUE TITLE
Continue prefetching as the user scrolls

### ISSUE THREAD

**Issue by jadjoubran** [GoogleChromeLabs/quicklink#6]
Does it make sense to prefetch links as the user is scrolling?

Here's a screencast of an example where I'm reading a JavaScript usecase and when I scroll towards the end, it would be nice for quicklink to prefetch those 2 related usecases
Screencast link: https://photos.app.goo.gl/mHgwbTmoKYXmXudEA

**Comment by prateekrastogi** [comment]
Add me as one of the folk who want it.
