### ISSUE TITLE
assignment rather than comparison in conditional

### ISSUE THREAD

**Issue by magicspon** [GoogleChromeLabs/quicklink#62]
https://github.com/GoogleChromeLabs/quicklink/blob/master/src/prefetch.mjs

line 104.

```javascript
  if (conn = navigator.connection) {
    // Don't prefetch if the user is on 2G. or if Save-Data is enabled..
    if ((conn.effectiveType || '').includes('2g') || conn.saveData) return;
  }
```

is that right?

**Comment by addyosmani** [comment]
I asked @lukeed about this change as we landed it during a round of code-golfing. The way this works is it evaluates `conn`, reuses the unused parameter instead of doing a complete var declaration and if () follow up. It assigns `nav.connection` to `conn` then if `conn` has a value it continues. 

```js
function prefetcher(url, isPriority, conn) {
  if (preFetched[url]) {
    return;
  }

  if (conn = navigator.connection) {
    // Don't prefetch if the user is on 2G. or if Save-Data is enabled..
    if ((conn.effectiveType || '').includes('2g') || conn.saveData) return;
  }
```

**Comment by magicspon** [comment]
mind.. blown!
