### ISSUE TITLE
Usage with barba/turbolinks/etc

### ISSUE THREAD

**Issue by magicspon** [GoogleChromeLabs/quicklink#63]
Heyo..

This looks super neat.

I'd like to be able to use this alongside something like barba.js to handle page transitions.

If I add an event listener to all of my links, would there be a way of checking to see if the url has already been downloaded, and if so trigger the page transition, and update the dom, without having to make another xhr request?

```javascript

function onClick(e) {
  // magic code
  if(cached(e)) {
    startAnimation(cached(e).html)
    return
   }

   fetch(e.pathname).then(etc => etc(etc)).then((html) => startAnimation(html))
}

```

any thoughts? 

thanks

**Comment by lukeed** [comment]
We could solve the portion of _checking_ whether or not a link has been downloaded fairly easily, but it won't include the _content_ of the response.

The odds are that whatever URL you're animating towards will be cached in your browser due to the prefetching. So a second request to the same URL will resolve instantly, meaning you can setup the XHR calls & responses as normal

**Comment by magicspon** [comment]
> The odds are that whatever URL you're animating towards will be cached in your browser due to the prefetching. So a second request to the same URL will resolve instantly, meaning you can setup the XHR calls & responses as normal

I thought this might be the case.  If the url is in the browser cache, does that mean the `fetch()` call wouldn't have to actually make a request, and would resolve instantly?

**Comment by demianrenzulli** [comment]
Closing this older issue, 

The pending answer is that, if a given url is in the prefetch cache, subsequent `fetch()` requests for that resource will be picked up from there, as long as they are made in the window of time that the browser determines (in Chrome, they are kept in the prefetch cache for 5 minutes after which point `cache-control` rules for the resource apply).

**Comment by miguelperez** [comment]
So this should work normally with turbolinks, right?
