### ISSUE TITLE
shouldn't window.addEventListener (in readme) use passive and/or once ?

### ISSUE THREAD

**Issue by LifeIsStrange** [GoogleChromeLabs/quicklink#64]
As it doesn't use Event.preventDefault(), it should use the passive boolean to save a few cpu time.

cf: https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

I am less sure, but quicklink() is called once and if there is a full reload, the addeventlistener is redownloaded.
So the once boolean should be used ? (it will automatically remove the listerner after it as been called once.
cf: https://developers.google.com/web/updates/2016/10/addeventlistener-once

So the readme should have:
window.addEventListener('load', {passive: true, once: true}, () =>{
            quicklink();
        });

(I may be wrong !)

**Comment by kurtextrem** [comment]
load is async, which means prevent default and passive doesn't change anything. 
load also only gets fired once, so once is also not needed

**Comment by LifeIsStrange** [comment]
Thanks for explaining !
