### ISSUE TITLE
Set does not work in <IE11

### ISSUE THREAD

**Issue by rdmurphy** [GoogleChromeLabs/quicklink#67]
Hello! 👋

Not flagging this to suggest it *should* work in anything below IE11, but the README currently says `quicklink` supports IE9+ as long as you have an Intersection Observer polyfill. However [`Set` is not available](https://github.com/GoogleChromeLabs/quicklink/blob/master/src/index.mjs#L20) until IE11. I think a user would need to have a Set polyfill in place to ensure it works that far back?

Apologies if I'm missing something! But wanted to flag just in case.

**Comment by tharun208** [comment]
Hi,
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
By Going through this documentation, You can see that , ie11 doesnot have `New Set()` options

**Comment by addyosmani** [comment]
Thanks for filling this issue. We should update the README with a reference to Babel's polyfills, or specifically, importing a shim for `Set()` to work around this problem for IE11 users https://github.com/zloirock/core-js/blob/master/README.md or 
https://github.com/paulmillr/es6-shim/blob/master/README.md.

**Comment by rdmurphy** [comment]
@addyosmani 👋 After doing another pass I think it may [need to mention `Array.from` too](https://github.com/GoogleChromeLabs/quicklink/blob/master/src/index.mjs#L93)? IE doesn't support it at all, unfortunately.

@tharun208 IE11 is fine with a bare `new Set()` without parameters (and the other uses of Set in `quicklink`), it's when you try to pass an interable in it gets mad.

```js
var set = new Set([1, 2, 3]); // IE11 will be upset about this
```

**Comment by addyosmani** [comment]
@rdmurphy 👋 I've just landed https://github.com/GoogleChromeLabs/quicklink/commit/aa40490cdf0622a3e8fa7384cee5c22b777a375f. Could you let me know if there's anything more you think we should add?

**Comment by rdmurphy** [comment]
@addyosmani Looks good to me! 🙌

**Comment by addyosmani** [comment]
Awesome. Closing this now that it's documented. Cheers! :)
