### ISSUE TITLE
Unwanted behavior of the library

### ISSUE THREAD

**Issue by fkeloks** [GoogleChromeLabs/quicklink#71]
Hello,

I just realized something after noticing a "bug" on my site using [Laravel](https://laravel.com/):

The pages of the site using the library "pre-load", the php sessions record this load and propel unwanted behaviors.

For example, Laravel's `back()` function, which redirects to the previous page, redirects the user to a random page because it is pre-loaded by the browser.

It will be necessary to be able to say to the backend not to record this pre-loading.

**Comment by lukeed** [comment]
This can't be `quicklinks`'s concern. If you have links that you _know_ cannot be pre-fetched (for whatever reason) you have to use the [`ignores` option](https://github.com/GoogleChromeLabs/quicklink#api)

You can see an example of this [here](https://github.com/GoogleChromeLabs/quicklink#custom-ignore-patterns).

**Comment by addyosmani** [comment]
@lukeed is correct here that the `ignores` option is our recommended solution to this issue. 

As `quicklink` aims to be a generic solution, if it's causing issues with Laravel's `back()` function, we would suggest whichever (random) URLs are causing this should be ignored. A good example of these types of pages are logout/login URLs.
