### ISSUE TITLE
Feature request: ability to set rough link fetching order

### ISSUE THREAD

**Issue by mherchel** [GoogleChromeLabs/quicklink#72]
I would love the ability to set a rough "order" on  the prefetching of links through something like:

```js
quicklink({
  order: [
    (uri, elem) => {
      const importantSelector = '.primary a';
      if (elem.matches(importantSelector)) return 0; // Zero would indicate super important;
    }
  ]
});
```

![image](https://user-images.githubusercontent.com/1605905/50562833-a104c800-0ce5-11e9-8072-51ed2a18d345.png)

**Comment by briantully** [comment]
As a workaround, can you call quicklink() more than once to emulate this?  For example:

`
const importantSelector = '.primary a';
quicklink({
  el: importantSelector
});

const secondarySelector = '.secondary a';
quicklink({
  el: secondarySelector
});
`

**Comment by lukeed** [comment]
As @briantully said, you would have to make two separate calls. 

Alternatively, if you want to avoid making two calls, an "ordered list" of URLs/links is what the `urls` option is for:

```js
quicklink({ 
  urls: [].concat(contentLinks, sidebarLinks).map(x => x.href)
  // ^ ordered by group
});
```

Although, do note that all requests are dispatched at the same time & won't necessarily respect the order anyway (see [here](https://github.com/GoogleChromeLabs/quicklink/blob/master/src/index.mjs#L90)). If you _really_ want to ensure `sidebar`'s requests are delayed, you'd need to split it into two `quicklink({ el })` calls with some arbitrary delay timer.

**Comment by demianrenzulli** [comment]
As discussed offline, it seems like it's better to close this one now.
The reason being that It's difficult to make any guarantees around link fetching order. One way of achieving something similar would be implementing a more clear queue but even then, given we're relying on `requestIdleCallback` for when to make these calls, it's hard to guarantee the resulting behavior would be what is expected in this request.
