### ISSUE TITLE
IE11 doesn't seem to play ball with quicklink();

### ISSUE THREAD

**Issue by willstocks-tech** [GoogleChromeLabs/quicklink#77]
So, I've been having some fun with this over the past couple of days - everything is fine and dandy in Chrome - I'm yet to test other browsers such as Safari and Firefox!
However on IE11, as soon as I call `quicklink();` (after polyfilling!) IE just stops completely.
Any ideas/pointers as to where I'm going wrong!
```
//This function is called if InterserctionObserver is not natively 
//supported by the browser. The function takes 1 argument - URL.
//It is at this point that we polyfill the feature using polyfill.io
//based on the URL checkIntersectionObserver passes on line 49.
function loadIntersectionObserver(url) {
	return new Promise(function(resolve, reject) { 
		var script = document.createElement('script'); 
		script.src = url; 
		document.getElementsByTagName('body')[0].appendChild(script); 
		console.log('Grabbing IntersectionObserver polyfill from: ', script.src);
		script.onload = resolve;
		script.onerror = reject; 
	});
}
function loadquicklink() {
	return new Promise(function(resolve, reject) { 
			var qlscript = document.createElement('script'); 
			qlscript.src = 'https://cdn.jsdelivr.net/npm/quicklink@1.0.0/dist/quicklink.umd.js'; 
			qlscript.defer = true; 
			document.getElementsByTagName('body')[0].appendChild(qlscript);
			console.log('Grabbing quicklink JS!')
			qlscript.onload = resolve;
			qlscript.onerror = reject; 
		});
}
//This function checks whether we need to polyfill IntersectionObserver or not
//If we don't, we can use the native API. If we do need to, then we go to the 
//loadIntersectionObserver function to polyfill the functionality.
function checkIntersectionObserver() {
	if ( 
		'IntersectionObserver' in window && 
		'IntersectionObserverEntry' in window 
	) {
		console.log( 'Nice one - your browser supports IntersectionObserver. No polyfills necessary!' );
		return loadquicklink();
	} else { 
		console.log( "Ahhh, your browser doesn't support IntersectionObserver. I'm gonna have to polyfill it so stuff works. Hang on one sec!" );
		return loadIntersectionObserver(
			'https://polyfill.io/v2/polyfill.js?features=IntersectionObserver&callback=loadquicklink' 
		);
	}
}
window.onload = function quicklinkloaded() {
	checkIntersectionObserver().then( 
		function() { 
			console.log( 'Aha! Everything is ready! Calling quicklink to get potential future pages ready for you to visit in advance!' );
			quicklink(); 
			console.log( "Et voila! We're now prefetching things you might click on - hopefully that speeds things up for you!!!" );
		},
		function() { 
			console.log( "So there was an issue polyfilling IntersectionObserver, which means that I can't preload future pages for you. Sorry! :(" );
			console.log( "If you want this to work, I'd recommend upgrading to a browser that supports IntersectionObserver natively. You can find out which browsers do by visting: https://caniuse.com/#feat=intersectionobserver" );
		}
	);
}
```
Note: Please excuse my messy code - this one is a learning curve for me and I'm fairly new to JS :)

**Comment by willstocks-tech** [comment]
In Chrome, I see the
`			console.log( "Et voila! We're now prefetching things you might click on - hopefully that speeds things up for you!!!" );`
And I can see in the network tab in devtools that pages are being prefetched. However on IE it just stops after:
`			console.log( 'Aha! Everything is ready! Calling quicklink to get potential future pages ready for you to visit in advance!' );`

**Comment by malchata** [comment]
FWIW, Quicklink crashes on IE because IE doesn't natively support Object.assign:

![image](https://user-images.githubusercontent.com/1635238/51540748-d308d600-1e1c-11e9-85eb-af0d25b1c825.png)

You could use [this transform](https://babeljs.io/docs/en/babel-plugin-transform-object-assign) in your project's Babel config to transform it to something IE can understand.

**Comment by willstocks-tech** [comment]
Aha - would've been useful for me to investigate a little more eh?

I've been working on something where I conditionally polyfill features for specific scripts. Might be of use for some (I'm not using Babel): https://github.com/willstocks-tech/dynamically-polyfill-features-for-a-script/blob/master/dynamicpolyfill.js

I'll tweak my little script from `var mayneedpolyfilling = ['IntersectionObserver', 'dialog']; \\dialog is just an example of a non-native feature - first I found` to: `var mayneedpolyfilling = ['IntersectionObserver', 'Object.assign'];` - that should take care of polyfilling that for browsers that need it (aka IE)

**Comment by midzer** [comment]
Just got polyfills for quicklink working manually. You need them for:
* Object.assign
* Array.from
* Array.forEach
* Array.includes
