### ISSUE TITLE
Consider allowing quicklink to fail softly if IntersectionObserver isn't available.

### ISSUE THREAD

**Issue by malchata** [GoogleChromeLabs/quicklink#79]
I just recently launched a new web site that uses quicklink. It's impressive, and improves the perception of speed to a point where a static website feels almost like an SPA at times. Good work!

One thing I noticed, though, is that quicklink crashes when Intersection Observer is not available. I'm aware that the documentation recommends a polyfill, but do you think it would make sense to fail softly when Intersection Observer is unavailable? Perhaps using [this check](https://github.com/w3c/IntersectionObserver/blob/master/polyfill/intersection-observer.js#L16-L18) and using `console.warn`?

In any event, great work on this. This script has tremendous utility in improving perceived performance, and I look forward to using it in future projects.

**Comment by addyosmani** [comment]
I've heard from a few developers that they would like quicklink to either gracefully fail if IO is not available or provide some form of built-in fallback that still accomplishes some of the same benefits. 

@lukeed I'd love your two cents here. A fallback (using `getBoundingClientRect()` or otherwise) would have _some_ cost to the core bundlesize. We could probably accomplish a graceful failure using `console.warn()` with a lot less cost.

**Comment by malchata** [comment]
FWIW, I fallback to scroll handlers/`getBoundingClient()` in my lazy loading library, but I think maybe using `console.warn` would be the way to go here. Just my two.

**Comment by lukeed** [comment]
That's fair! I think we can detect early (within the default export) if IO is supported. We would then bail if it can't do anything. 

I think, right off the bat, that we need to export the current default as a named function (eg "listen") and then make `preload` and named export as well. That would solve the current problem of not being able to access `preload` in a prebuilt setting like unpkg. This also allows non-IO browsers to easily call preload on demand.

As for fallback vs bail -- I think we should bail. If we offer an alternate, equal solution, that should just be the solution.

We've discussed scroll listeners in the past (which is my preferred approach) but including a fully-functional fallback is 2x the code for 1 purpose.
