### ISSUE TITLE
整了一个简单的中文教程和介绍！

### ISSUE THREAD

**Issue by xmt1139057136** [GoogleChromeLabs/quicklink#82]
整了一个简单的中文教程和介绍！

[http://www.xttblog.com/?p=3799](http://www.xttblog.com/?p=3799)

欢迎大家共同学习交流！

**Comment by chaihongjun** [comment]
今天正准备试一试这个东西，直接用它的quick start方式

**Comment by chaihongjun** [comment]
官方已经有了中文文档：https://github.com/GoogleChromeLabs/quicklink/tree/master/translations/zh-cn

**Comment by Mirror198829** [comment]
> 今天正准备试一试这个东西，直接用它的quick start方式

不知楼主 试了结果如何？

**Comment by chaihongjun** [comment]
> > 今天正准备试一试这个东西，直接用它的quick start方式
> 
> 不知楼主 试了结果如何？

对当前页面加载没什么效果，但是对其他的确实有效果的。我们之前也有过类似的想法，鼠标指向a标签的链接，我们做prefetch。这里是针对浏览器视口，拉动滚动条的时候发现确实会预先加载。不管怎么说还是有点效果的。你可以试一试。

**Comment by Mirror198829** [comment]
@chaihongjun  本人在vue工程引入quicklink，DomContentedLoad测试结果并无差异

**Comment by chaihongjun** [comment]
@Mirror198829 你的单页吧？我用的多页测试的。你是不是添加方式不对，文档介绍的是多页的。单页的要在路由里面配置。

**Comment by sleagon** [comment]
在阿里云的cdn上托管了一个1.0.0的，生产环境可用的，支持polyfill-service，不需要额外引用polyfill了

http://polyfill.alicdn.com/static/sdk?sdks=quicklink/1.0.0/index.umd.js&polyfills=IntersectionObserver

**Comment by demianrenzulli** [comment]
Hi folks, 

Sorry I don't speak Chinese, but I managed to translate this issue, and seems you guys were discussing the need for documentation in Chinese, which fortunately is now available here: https://github.com/GoogleChromeLabs/quicklink/tree/master/translations/zh-cn.

Seems like there were some discussions also SPA support, which is being currently discussed as well.

This issue hasn't been updated in a long time now, so I guess that's everything you need at the moment.
Feel free to reopen it, or ask separately if we can help you somehow.

Cheers.
