### ISSUE TITLE
A single link with all related polyfills.

### ISSUE THREAD

**Issue by sleagon** [GoogleChromeLabs/quicklink#83]
Could we add a link in Readme to provide a cdn version quicklink ? The polyfills is built on polyfill-service, so it is dynamic.

Here is the link:
https://b.alicdn.com/s/static/sdk?sdks=quicklink/1.0.0/index.umd.js&polyfills=IntersectionObserver,Set,Array.from

**Comment by addyosmani** [comment]
Thanks. I'm not as familiar with the alicdn origin - it _looks_ like this is using the Alibaba Cloud / Cloud SDK. Is there documentation available about how the above URL works?

**Comment by sleagon** [comment]
Yes, this link will be served by akamai cdn outside china and alibaba cdn inside china. We just start to use it in our website, we think it may help some other people who want to use it. Feel free to close this issue anyway~
