### ISSUE TITLE
Why not a chrome plugin?

### ISSUE THREAD

**Issue by kootenpv** [GoogleChromeLabs/quicklink#85]
I am wondering why there is no chrome plugin that would load this on any page? Am I overseeing something?

**Comment by chaihongjun** [comment]
If  following your thoughts it may involve the ownership of the websites, some webmasters may not want their website to be forced to do something. I guess

**Comment by addyosmani** [comment]
Chrome has a built in feature for attempting to preload/prefetch web pages that has existed for some time. As per the comment above, doing anything automated this way not be what the site authors wanted. Think of quicklink as providing them more control over that capability. For details on the built-in approach (closest thing we have to a plugin) see https://www.technipages.com/google-chrome-prefetch
