### ISSUE TITLE
Not working on Firefox v65

### ISSUE THREAD

**Issue by PeterDaveHello** [GoogleChromeLabs/quicklink#89]
Hello,

I've tested quicklink using the `test/` page with Chrome/Chromium which works very well, however, it doesn't work at all with `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0` (On `Linux Mint 19.1 Tessa`), both the current latest 8c007ab8fb189071d6add4b134252f2c554c0e1c and [v1.0.0](https://github.com/GoogleChromeLabs/quicklink/tree/1.0.0), and there is no error or warning message in the developer tool console. I haven't tested on other environments yet.

Not sure if anyone else has the same issue and what should I do to help locate that issue, let me know if I missed anything or how can I help please, thank you!

**Comment by dieulot** [comment]
The page will get redownloaded in Firefox if it’s not cached. Also note that uBlock Origin disables prefetching.

**Comment by PeterDaveHello** [comment]
Thanks, I've cleared the cache and disabled the uBlock Origin, but didn't work still 😓

**Comment by dieulot** [comment]
I mean that without cache headers the page will get redownloaded (thus it won’t improve the page load speed.)

Regarding uBlock Origin, you need to disable it completely, using the big blue button is not enough (it only disable filters).

**Comment by demianrenzulli** [comment]
Closing this one, as it has been opened for a while without response.

@PeterDaveHello, please, let us know in case you need any additional help on this.
