### ISSUE TITLE
what is the .mjs file?

### ISSUE THREAD

**Issue by sishenhei7** [GoogleChromeLabs/quicklink#90]
Sorry for my innocence but can someone tell me what is the .mjs file?

**Comment by coliff** [comment]
MJS is:

> a source code file containing an ES Module (ECMAScript Module) for use with a Node.js application. MJS files are written in JavaScript, and may also use the .JS extension outside of the Node.js context. ES Modules allow web and application developers to organize code into smaller reusable components.

REF: https://fileinfo.com/extension/mjs
