### ISSUE TITLE
requestIdleCallback does not exist in bundled quicklink.js 

### ISSUE THREAD

**Issue by victor-tkachenko** [GoogleChromeLabs/quicklink#93]
https://unpkg.com/quicklink@1.0.0/dist/quicklink.umd.js

You can open this link and verify it by search

**Comment by demianrenzulli** [comment]
Seems like an issue related to that particularly version, in the current one: 

https://unpkg.com/quicklink@2.0.0-alpha/dist/quicklink.umd.js

it is available.
