### ISSUE TITLE
how can i ignore some domain?

### ISSUE THREAD

**Issue by chaihongjun** [GoogleChromeLabs/quicklink#96]
I dont know how to ignore some domian the third party I dont want to fetch.:

`quicklink({
  ignores: [
    /\/api\/?/,
    uri => uri.includes('.zip'),
    (uri, elem) => elem.hasAttribute('noprefetch')
  ]
});`

**Comment by mherchel** [comment]
By default, Quicklink will ignore all domains except for the origin domain. There is the `origins` options within the API that contains an "array of URL hostname strings that are allowed to be prefetched. Defaults to the same domain origin, which prevents any cross-origin requests."

**Comment by chaihongjun** [comment]
> By default, Quicklink will ignore all domains except for the origin domain. There is the `origins` options within the API that contains an "array of URL hostname strings that are allowed to be prefetched. Defaults to the same domain origin, which prevents any cross-origin requests."

@mherchel 
So that is what  it is.
But I found that some third party resources  wont be ignored ...
Oh，I read the wrong thing.

**Comment by chaihongjun** [comment]
@mherchel  thank u very much
