### ISSUE TITLE
demo site css may be broken.

### ISSUE THREAD

**Issue by konojunya** [GoogleChromeLabs/quicklink#99]
<img width="1440" alt="スクリーンショット 2019-05-27 18 58 36" src="https://user-images.githubusercontent.com/12035578/58412641-d5708a80-80b1-11e9-8f51-c4200329ef9b.png">

The demo site css may be broken. I don't think this repository is managed in `demos` dir , so if you leave this fix to me please let me know the repository.

**Comment by coliff** [comment]
Hi @konojunya - that effect on the menus is present on the main https://www.blog.google/ site so I assume it looks that way intentionally. I don't think this is a bug with quicklink and that sites code isn't in this repo so I guess you can close this issue.

**Comment by konojunya** [comment]
That's right.
